### ISSUE TITLE
Find a way to reach the backend 

### ISSUE THREAD

**Issue by ia3andy** [fabric8-launcher/launcher-creator-welcome-app#11]
Proposed solution is to use an `nginx` image and proxy calls directly to the backend service (using oc internal urls)

**Comment by quintesse** [comment]
This is what the Node team suggests using: https://developers.redhat.com/blog/2018/10/23/modern-web-applications-on-openshift-part-2-using-chained-builds/

A chained build approach where we'd have full control over the configuration to use for nginx

**Comment by ia3andy** [comment]
@quintesse Here is `service.welcome.yaml` to generate from the creator.

Of course some value need to be adapted:
- WELCOME_APP_CONFIG 
- BACKEND_SERVICE_NAME
```yaml
apiVersion: v1
kind: Template
parameters:
  - name: SOURCE_REPOSITORY_URL
    description: The source URL for the application
    displayName: Source URL
    value: https://github.com/fabric8-launcher/launcher-creator-welcome-app
    required: true
  - name: SOURCE_REPOSITORY_REF
    description: The branch name for the application
    displayName: Source Branch
    value: master
    required: true
  - name: SOURCE_REPOSITORY_DIR
    description: The location within the source repo of the application
    displayName: Source Directory
    value: .
    required: true
  - name: OUTPUT_DIR
    description: The location of the compiled static files from your web apps builder
    displayName: Output Directory
    value: build
    required: false
  - name: WELCOME_APP_CONFIG
    description: The configuration for the welcome app
    displayName: Welcome App Configuration
    value: >-
      {"applicationName":"chained-build-welcome-app","applicationUrl":"/api","capabilities":[{"module":"rest"}]}
    required: true
  - name: BACKEND_SERVICE_NAME
    description: The backend service name for the welcome app
    displayName: Backend service name
    value: chained-build-welcome-app-vertx
    required: true
objects:
- apiVersion: v1
  kind: ImageStream
  metadata:
    name: welcome-app-build-output
  spec: {}
- apiVersion: v1
  kind: ImageStream
  metadata:
    name: welcome-app-on-server-output
  spec: {}
- apiVersion: v1
  kind: ImageStream
  metadata:
    name: webapp-builder
  spec:
    tags:
    - name: latest
      from:
        kind: DockerImage
        name: nodeshift/centos7-s2i-web-app:latest
- apiVersion: v1
  kind: ImageStream
  metadata:
    name: server-image
  spec:
    tags:
    - name: latest
      from:
        kind: DockerImage
        name: 'centos/nginx-18-centos7:latest'
- apiVersion: v1
  kind: BuildConfig
  metadata:
    name: welcome-app-build
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: welcome-app-build-output:latest
    postCommit: {}
    resources: {}
    source:
      git:
        uri: ${SOURCE_REPOSITORY_URL}
        ref: ${SOURCE_REPOSITORY_REF}
      contextDir: ${SOURCE_REPOSITORY_DIR}
      type: Git
    strategy:
      type: Source
      sourceStrategy:
        env:
          - name: OUTPUT_DIR
            value: ${OUTPUT_DIR}
          - name: REACT_APP_WELCOME_APP_CONFIG
            value: ${WELCOME_APP_CONFIG}
          - name: BACKEND_SERVICE_NAME
            value: ${BACKEND_SERVICE_NAME}
        from:
          kind: ImageStreamTag
          name: webapp-builder:latest
        incremental: false
  status:
    lastVersion: 0
- apiVersion: v1
  kind: BuildConfig
  metadata:
    name: welcome-app-on-server-build
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: welcome-app-on-server-output:latest
    postCommit: {}
    resources: {}
    source:
      type: Image
      images:
        - from:
            kind: ImageStreamTag
            name: welcome-app-build-output:latest
          paths:
            - destinationDir: .
              sourcePath: /opt/app-root/output/.
    strategy:
      type: Source
      sourceStrategy:
        from:
          kind: ImageStreamTag
          name: server-image:latest
        incremental: true
    triggers:
      - type: ConfigChange
      - type: ImageChange
        imageChange: {}
      - type: ImageChange
        imageChange:
          from:
            kind: ImageStreamTag
            name: welcome-app-build-output:latest
  status:
    lastVersion: 0
- kind: DeploymentConfig
  apiVersion: v1
  metadata:
    name: welcome-app-deployment
    creationTimestamp: null
    labels:
      app: welcome-app
      apptype: welcome
  spec:
    strategy:
      resources:
        {}
    triggers:
      - type: ConfigChange
      - type: ImageChange
        imageChangeParams:
          automatic: true
          containerNames:
            - welcome-app-on-server-output
          from:
            kind: ImageStreamTag
            name: welcome-app-on-server-output:latest
    replicas: 1
    test: false
    selector:
      app: placeholder-app-label-d46881878f594a2dadfd963843452aab
      deploymentconfig: welcome-app-deployment
    template:
      metadata:
        creationTimestamp: null
        labels:
          app: placeholder-app-label-d46881878f594a2dadfd963843452aab
          deploymentconfig: welcome-app-deployment
      spec:
        containers:
          - name: welcome-app-on-server-output
            image: welcome-app-on-server-output:latest
            ports:
              - containerPort: 8080
                protocol: TCP
            resources:
              {}
            env:
              []
  status:
    latestVersion: 0
    observedGeneration: 0
    replicas: 0
    updatedReplicas: 0
    availableReplicas: 0
    unavailableReplicas: 0
- kind: Service
  apiVersion: v1
  metadata:
    name: welcome-app-service
    creationTimestamp: null
    labels:
      app: welcome-app
      apptype: welcome
  spec:
    ports:
      - name: 8080-tcp
        protocol: TCP
        port: 8080
        targetPort: 8080
    selector:
      app: placeholder-app-label-d46881878f594a2dadfd963843452aab
      deploymentconfig: welcome-app-deployment
  status:
    loadBalancer:
      {}
- apiVersion: v1
  kind: Route
  metadata:
    name: welcome-app-route
    labels:
      app: welcome-app
      apptype: welcome
  spec:
    port:
      targetPort: 8080-tcp
    to:
      kind: Service
      name: welcome-app-service

```
